### ISSUE TITLE
Impossible to update entity when using custom entity manager

### ISSUE THREAD

**Issue by fautor** [Dukecity/CommandSchedulerBundle#102]
If you had configured custom entity manager for scheduler you can't save existing entity due to error "Name: This value is already used". It happens because attribute `#[UniqueEntity(fields: ["name"])]` in class ScheduledCommand works only with default em and to fix this problem you should add manualy this param to attribute: `#[UniqueEntity(fields: ["name"], em: 'scheduler')]`

**Comment by Chris53897** [comment]
@fautor Can you please check if the linked PR does fix your issue?

Or can you create a new PR with a working solution?

**Comment by fautor** [comment]
Unfortunatly, right way to fix this problem is passing em to attribute like variable, but this impossible due to PHP restrictions, so linked PR is work solution, I've checked it. And it would be great to merge it in main branch (I use 5.x)

**Comment by Chris53897** [comment]
Thanks for testing.
I will check as soon as i have some free time.

**Comment by Chris53897** [comment]
@fautor I will close this as supported with https://github.com/Dukecity/CommandSchedulerBundle/releases/tag/v5.0.9
