### ISSUE TITLE
Remove symfony/debug-bundle from prod dependencies

### ISSUE THREAD

**Issue by vasilvestre** [Dukecity/CommandSchedulerBundle#13]
Hello?

I just found out that symfony/debug-bundle wasn't in dev dependencies. Is it used in actual code or to debug during dev ?
 https://github.com/Dukecity/CommandSchedulerBundle/blob/5a58ae82ca565535fbaae0424b32addbea616783/composer.json#L33

**Comment by Chris53897** [comment]
Sorry, i did not see an E-Mail and just noticed your message. I will check it
