### ISSUE TITLE
Can symfony/inflector be removed?

### ISSUE THREAD

**Issue by Knallcharge** [Dukecity/CommandSchedulerBundle#19]
After installing version 3 I get this composer-warning during composer update:
"Package symfony/inflector is abandoned, you should avoid using it. Use use `EnglishInflector` from the String component instead instead."

I couldn't find the usage of inflector in the bundle, so probably symfony/inflector can just be removed from composer.json?

**Comment by Chris53897** [comment]
Thanks for mention this.

[Test-runs](https://github.com/Dukecity/CommandSchedulerBundle/actions/runs/1113774375) look good.
inflector was already removed from 4.x branch. https://github.com/Dukecity/CommandSchedulerBundle/issues/15#issuecomment-884469979
I made a new [Release](https://github.com/Dukecity/CommandSchedulerBundle/releases/tag/v3.0.11)

**Comment by Knallcharge** [comment]
Great. Thanks for keeping this package alive :)

**Comment by Chris53897** [comment]
Will try my best ;)
