### ISSUE TITLE
Is doctrine/doctrine-migrations-bundle necessary?

### ISSUE THREAD

**Issue by Knallcharge** [Dukecity/CommandSchedulerBundle#23]
Hi,
I just tried version 4 of the CommandSchedulerBundle and was wondering if the migrations-bundle is really necessary.
I understand that there are queries to be executed to get the library up and running, but wouldn't it be sufficient to just execute "doctrine:schema:update" when updating?
The reason I'm asking is that I don't use the migrations-bundle (for some reasons) and thought it was kind of strange to put it into the requirements while people who use it, will already have it in their root-requirements. I found that updating to version 4 of the CommandSchedulerBundle will blow up my autoloader by ca. 500 classes which is quite a lot especially considering that the migrations-bundle is probably only used once when installing the CommandSchedulerBundle (or upgrading it).
So maybe I'm not getting the actual reason for including the migrations-bundle, but maybe you want to reconsider the requirement and let the users decide whether to use it or not. If version 4 can't do without the migrations-bundle, I can use version 3 as well, no problem :)
Kind regards and thanks for your continued work on the library!

**Comment by Chris53897** [comment]
Hi,

that is because of a simple reason. This dependency is from the org. repo. ;)
I guess you are right, with the assumption that most projects have doctrine-migrations-bundle in root.

Are you willing to provide a PR for Code and Docs?

Greetz

**Comment by Knallcharge** [comment]
Sure, just made some small changes. I'm not very familiar with code changes via the github-webpage, turned out I created to pull requests, one for each file.
