### ISSUE TITLE
Wrong asset filename in layout view

### ISSUE THREAD

**Issue by aradzimski** [Dukecity/CommandSchedulerBundle#29]
![image](https://user-images.githubusercontent.com/32592648/149106907-835403a4-1ca9-4ce3-8f4a-b94acff44941.png)

**CommandSchedulerBundle/Resources/views/layout.html.twig**

One of the linked css files is named 'dataTables.min.css', but in **CommandSchedulerBundle/Resources/public/css/** there is file named 'datatables.min.css'.

**Comment by NaincyKumariKnoldus** [comment]
Hello @aradzimski Can I solve this issue please.

**Comment by aradzimski** [comment]
Sure

**Comment by NaincyKumariKnoldus** [comment]
Hey @aradzimski I have a raised a PR for this. Please Review it and merge this.
Thanks!
