### ISSUE TITLE
TEST SF-6.1-DEV and SF-6.0

### ISSUE THREAD

**Issue by TechSupportPlugnotes** [Dukecity/CommandSchedulerBundle#31]
Hello, do you continue to maintened this project ?
Because i used this bundle since SF 2.8.
And i would like prepare new project with 6.1-dev, but i have some errors

`Cannot autowire service "Dukecity\CommandSchedulerBundle\Controller\ApiController": argument "$container" of method "Symfony\Bundle\FrameworkBundle\Controller\AbstractController::setContainer()" references interface "Psr\Container\ContainerInterface" but no such service exists. Available autowiring aliases for this interface are: "$parameterBag".`

Thanks 2 feedback :)

**Comment by Chris53897** [comment]
Hi, can you try the `dev`-Branch? dukecity/command-scheduler-bundle": "dev-dev"
It is still under development.

**Comment by TechSupportPlugnotes** [comment]
Hi thanks a lot your answer.
I have tried the dev-dev and i have the previous error.
So the important answer was that you continue to develop and it's a good new.

**Comment by Chris53897** [comment]
Thanks for testing. I will work on that

**Comment by TechSupportPlugnotes** [comment]
Hello,
Just a review , after comment 

`/*    $services->set(ApiController::class)
        ->call('setManagerRegistry', [service('doctrine')])
        ->call('setManagerName', ['%dukecity_command_scheduler.doctrine_manager%'])
        ->call('setTranslator', [service('translator')])
        ->call('setLockTimeout', ['%dukecity_command_scheduler.lock_timeout%'])
        ->call('setLogger', [service('logger')])
        ->call('setCommandParser', [service(CommandParser::class)])
        ->tag('controller.service_arguments');*/`

I can use the dev-dev.

For my use and old version table i change also an another file but it's not important. But to pass the preview error i dot comment code before.

**Comment by Chris53897** [comment]
@TechSupportPlugnotes thanks. I will have a look as soon as possible.

**Comment by Chris53897** [comment]
@TechSupportPlugnotes I updated the `dev`-Branch. Can you please give it another try?

**Comment by TechSupportPlugnotes** [comment]
Hello,

I will test this on Wednesday. I took a few days off.

**Comment by Chris53897** [comment]
Great news. Thanks for testing

**Comment by Chris53897** [comment]
@TechSupportPlugnotes I made a new Release 5.0.0 (based on the dev-Branch). Can you switch to that release please. I want to delete the `dev`-Branch.

**Comment by TechSupportPlugnotes** [comment]
Yes no problem . Thanks.

Envoyé de mon iPhone
