### ISSUE TITLE
doctrine/persistence

### ISSUE THREAD

**Issue by bilik** [Dukecity/CommandSchedulerBundle#36]
Why does it block the doctrine/persistence version on 2.2.2?

**Comment by Chris53897** [comment]
It is already changed in `dev-master`.
https://github.com/Dukecity/CommandSchedulerBundle/blob/master/composer.json

I just made a new Release [5.0.1](https://github.com/Dukecity/CommandSchedulerBundle/releases/tag/v5.0.1)
