### ISSUE TITLE
cannot remove (null) logfile field 

### ISSUE THREAD

**Issue by scu-msantini** [Dukecity/CommandSchedulerBundle#43]
after setting a logfile, I can only change the file but not remove it again. I need to null the LOG_FILE field on database level. using V5.0.2 

Exception Message:
Line 274: Expected argument of type "string", "null" given at property path "logFile".

#0 /var/www/redirector/vendor/symfony/property-access/PropertyAccessor.php(179): Symfony\Component\PropertyAccess\PropertyAccessor::throwInvalidArgumentException() 
#1 /var/www/redirector/vendor/symfony/form/Extension/Core/DataAccessor/PropertyPathAccessor.php(69): Symfony\Component\PropertyAccess\PropertyAccessor->setValue() 
#2 /var/www/redirector/vendor/symfony/form/Extension/Core/DataAccessor/ChainAccessor.php(54): Symfony\Component\Form\Extension\Core\DataAccessor\PropertyPathAccessor->setValue() 
#3 /var/www/redirector/vendor/symfony/form/Extension/Core/DataMapper/DataMapper.php(87): Symfony\Component\Form\Extension\Core\DataAccessor\ChainAccessor->setValue() 
#4 /var/www/redirector/vendor/symfony/form/Form.php(642): Symfony\Component\Form\Extension\Core\DataMapper\DataMapper->mapFormsToData() 
#5 /var/www/redirector/vendor/symfony/form/Extension/HttpFoundation/HttpFoundationRequestHandler.php(109): Symfony\Component\Form\Form->submit() 
#6 /var/www/redirector/vendor/symfony/form/Form.php(503): Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler->handleRequest() 
#7 /var/www/redirector/vendor/dukecity/command-scheduler-bundle/Controller/DetailController.php(28): Symfony\Component\Form\Form->handleRequest() 
#8 /var/www/redirector/vendor/symfony/http-kernel/HttpKernel.php(163): Dukecity\CommandSchedulerBundle\Controller\DetailController->edit() 
#9 /var/www/redirector/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw() 
#10 /var/www/redirector/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle() 
#11 /var/www/redirector/public/index.php(30): Symfony\Component\HttpKernel\Kernel->handle() 
#12 {main}

**Comment by Chris53897** [comment]
Hi. That looks like an easy PR, (on first sight). Maybe you want to do the PR?

**Comment by scu-msantini** [comment]
i cannot create branches (permission denied). 
anyway, Entity/ScheduledCommand.php just needs a ? before string on line 176.
public function setLogFile(?string $logFile): ScheduledCommand

**Comment by Chris53897** [comment]
Did you made a fork first?
I made a PR and you can test it with "dev-master".
It can be set per internal calls. But i am not sure if you want it in the default-form.
Maybe that will not work, and empty_data has to be explicit be set.

Please have a look

**Comment by scu-msantini** [comment]
I installed like: dukecity/command-scheduler-bundle": "dev-feat/allow-logfiles-nullable"
i can now add/remove logfiles as expected. I didnt test much else - scheduler still works.

**Comment by Chris53897** [comment]
Great news. I made a new release https://github.com/Dukecity/CommandSchedulerBundle/releases/tag/v5.0.3
and will close this one.
