### ISSUE TITLE
UnlockCommand unlocking itself

### ISSUE THREAD

**Issue by Knallcharge** [Dukecity/CommandSchedulerBundle#46]
When calling "scheduler:unlock --all" via the scheduler itself, the unlock-command is of course locked during the run of "scheduler:execute" which leads to the message "[ERROR] Skipping: Timeout for scheduled Command "unlock" has not run out." in the cron.log.

As this is the expected behavior but the error message  is pretty much obsolete and could be misleading, it could be skipped.

The necessary change would be replacing `$this->unlock($failedCommand);` in UnlockCommand (line 103) with
```
if ($failedCommand->getCommand() !== self::getDefaultName()) {
    $this->unlock($failedCommand);
}
```
What do you think?

**Comment by Chris53897** [comment]
Hi,
i merged it in master. Can you please confirm that it works correctly.
After that i can make a new release.

**Comment by Knallcharge** [comment]
Will try as soon as I can!

**Comment by Knallcharge** [comment]
Looks good to me, works as expected.

**Comment by Chris53897** [comment]
Thanks @Knallcharge 
I made a new release https://github.com/Dukecity/CommandSchedulerBundle/releases/tag/v5.0.4
