### ISSUE TITLE
Start schedule command with blocking throw an error

### ISSUE THREAD

**Issue by kl3sk** [Dukecity/CommandSchedulerBundle#72]
Hello,

Using `php bin/console scheduler:start -b` it returns 

```bash
In ExecuteCommand.php line 199:

  Attempted to call an undefined method named "clear" of class "Symfony\Component\Console\Output\NullOutput".
```

It seem due to the file `command-scheduler-bundle\Command\ExecuteCommand.php` line 197

Using Symfony 6.3.4 PHP 8.1

**Comment by Chris53897** [comment]
Thanks for reporting this. I guess this mode is not often used. Otherwise it would be reported already.

Are you up for a PR and adding tests?

**Comment by kl3sk** [comment]
Hello,

I just use it to quickly test the bundle, in fact I switch to something more used (eg. systemd).

I did not dig too much yet, I'll try to have a look.
