### ISSUE TITLE
Master -  composer PHP 8.2

### ISSUE THREAD

**Issue by pdias** [Dukecity/CommandSchedulerBundle#81]
I'm using PHP 8.1 and in the info says that are compatibilitie with PHP > 8.0.

Any idea to try to resolve this?

Thanks.

**Comment by Chris53897** [comment]
Hi. Yes the 5.x Branch is working with php > 8.0.2
https://packagist.org/packages/dukecity/command-scheduler-bundle#v5.0.7

You can install this bundle on any php version with Install infos from here.
https://github.com/Dukecity/CommandSchedulerBundle?tab=readme-ov-file#install 

Composer will find the supported version for you.

i prepared `master` already for 6.x.
I just updated README.md for the new infos.
https://github.com/Dukecity/CommandSchedulerBundle?tab=readme-ov-file#versions--dependencies
