### ISSUE TITLE
Start schedule command caching object

### ISSUE THREAD

**Issue by GayKevin** [Dukecity/CommandSchedulerBundle#90]
Hello,

I am encountering an issue in production mode on Symfony where updates to a command are not being recognized by the Start Scheduler script. However, when the command is run for the first time (in the infinite loop), it works as expected.

Upon investigation, I noticed that the object returned by the following line of code remains the same every time it is called:

```php
$commandsToExecute = $this->em->getRepository(ScheduledCommand::class)->findCommandsToExecute();
```

It appears that Doctrine is caching the object instead of querying the database again to check for any new updates.

I found that using Doctrine's clear() method resolves this issue. This method detaches all entities managed by the EntityManager, effectively clearing the cache and forcing Doctrine to query the database again the next time it needs data.

**Comment by kl3sk** [comment]
I didn't see this issue, it may be the cause of my problem: https://github.com/Dukecity/CommandSchedulerBundle/pull/89#issuecomment-1888813162

How you think this is fixable ?
